### ISSUE TITLE
[BUG]: Cannot read properties of undefined

### ISSUE THREAD

**Issue by vmcodes** [ArcBlock/did-connect#77]
# 🐛 Bug Report

Hello, I hope I'm at the right place 😅

## 详细描述

I am receiving this error when using @did-connect/react 2.1.33 and 2.1.35.

## 复现这个bug

This occurs when I attempt to use DID Connect.

## 截图或报错信息(可选)

![Screenshot from 2023-02-23 13-31-20](https://user-images.githubusercontent.com/30095385/221005769-2e11a3c7-9f0d-473c-930d-16433e87b3d0.png)

## 异常的行为

I never experienced this issue with Ant Design. However, I am with Chakra UI. I tried installing MUI as a dev dependency and a dependency as well.

## 期望的行为

A temporary past working version would be okay for now 

## 可能的解决方案(可选)

Thank you 🚀

**Comment by vmcodes** [comment]
The following packages are also not compatible, thank you!
    "@did-connect/react": "^2.1.35",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/material": "^5.11.10",
    "antd": "^5.1.7",

**Comment by wangshijun** [comment]
I am looking into the compatibility issue, and will provide an working example repo upon resolve, please stay tuned.

**Comment by wangshijun** [comment]
@vmcodes Here is a working blocklet that combines DID Connect and Chakra UI

https://github.com/wangshijun/did-connect-chakra-ui

The main compatibility issue is caused by theme conflicting between the 2 library, and can be workaround by https://github.com/wangshijun/did-connect-chakra-ui/blob/master/src/components/connect.jsx

I have verified this on my local dev blocklet server, both in dev and prod mode.

Please checkout to see if it works on your side.

**Comment by vmcodes** [comment]
Will do @wangshijun, thank you!

**Comment by vmcodes** [comment]
The wrapped connect workaround was perfect. Thanks!
